name: CTest on Push

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install cmake g++

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      run: cmake ../src/tests

    - name: Build and run tests
      working-directory: build
      run: cmake --build . --config Release && ctest --output-on-failure
